# Generated by Django 4.0.4 on 2022-04-29 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_alter_blogpost_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPostRich',
        ),
    ]
