# Generated by Django 4.0.4 on 2022-05-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_delete_blogpostrich'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Users Comments'},
        ),
    ]
